fix: filenames in schedule.tsv
TheAxonLab/hcph-sops pull request #395
Opened 2023-11-23 15:13 UTC by esavary

Related to #394

2023-11-23 15:31 UTC, acionca approved these changes
Looks good, I am just not sure why you would modify the column names from `_events` to `_edf`

2023-11-23 15:32 UTC, esavary commented
> Looks good, I am just not sure why you would modify the column names from `_events` to `_edf`

Yes, good catch that was not intentional.

2023-11-23 15:33 UTC, esavary commented on code/events/schedule.tsv
> +session	day	PE	dwi_edf	qct_edf	rest_edf	bht_edf
```suggestion
session	day	PE	dwi_events	qct_events	rest_events bht_events
```

2023-11-23 17:56 UTC, oesteban requested changes
We need to be careful when changing things. The goal of this PR, if addressing #394, should be limited to only those changes. That means:

- no unintentional errors such as the change of the tab in the header with spaces
- no addition of lines that were removed in other PRs for a reason. If you believe these lines should be added, then open another PR to drive the corresponding conversation. In this case, however, those lines were intentionally removed previously and moved to a different file (https://github.com/TheAxonLab/hcph-sops/blob/mkdocs/code/events/schedule-pilot-excl.tsv).

2023-11-23 17:56 UTC, oesteban commented on code/events/schedule.tsv
> +session	day	PE	dwi_events	qct_events	rest_events  bht_events
This needs to remain a tab.
```suggestion
session	day	PE	dwi_events	qct_events	rest_events	bht_events
```

2023-11-23 17:56 UTC, oesteban commented on code/events/schedule.tsv
> +36		RL	n/a	n/a	n/a	n/a
What's the point of this?
```suggestion
```

See https://github.com/TheAxonLab/hcph-sops/blob/mkdocs/code/events/schedule-pilot-excl.tsv

2023-11-23 17:56 UTC, oesteban commented on code/events/schedule.tsv
> +27	2023-11-02	AP	fixation_2023-11-02_19h29.37.833_1_session_27.log	n/a	n/a	n/a
```suggestion
```

https://github.com/TheAxonLab/hcph-sops/blob/mkdocs/code/events/schedule-pilot-excl.tsv

2023-11-23 17:56 UTC, oesteban commented on code/events/schedule.tsv
> +14	2023-10-26	LR	n/a	n/a	n/a	n/a
```suggestion
```

2023-11-23 19:07 UTC, oesteban commented
I guess this was closed by mistake?

2023-11-24 11:01 UTC, esavary commented
> I guess this was closed by mistake?

Yes, thanks for reopening

2023-11-24 16:06 UTC, merged